# Generated by Django 6.0.6 on 2026-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('phone', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='شماره تلفن همراه')),
                ('password', models.CharField(blank=True, max_length=120, null=True, verbose_name='گذرواژه')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='ایمیل')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخرین لاگین')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='بلاک شده / نشده')),
                ('is_customer', models.BooleanField(default=True, verbose_name='مشتری')),
                ('is_seller', models.BooleanField(default=False, verbose_name='فروشنده')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
        ),
    ]
