# Generated by Django 6.0.6 on 2026-07-04 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='شماره تلفن معتبر نیست.')], verbose_name='شماره تلفن همراه')),
                ('otp_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='کد تایید باید ۶ رقم باشد.')], verbose_name='کد موقت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('wrong_attempts', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='تعداد تلاش های اشتباه')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
            ],
            options={
                'verbose_name': 'کد موقت',
                'verbose_name_plural': 'کدهای موقت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='گذرواژه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='شماره تلفن معتبر نیست.')], verbose_name='شماره تلفن همراه'),
        ),
    ]
